-- llena tienda
DECLARE @TDA CHAR(2)
SET @TDA = '05'

-- COLOCA ESTADO ELIMINADO A TODOS LOS ARTICULOS QUE NO EXISTEN EN EL REAL COMO VIGENTES
update articulos set articulos.estado = 'E' where articulos.tienda = @TDA
AND articulos.CODIGO  NOT  IN
(SELECT A1.CODIGO
FROM ARTICULOS AS A1 , RSFACCAR..AL0012ARTI AS A2
WHERE AR_CESTADO='v' AND AR_CFSTOCK='s' AND  ar_cfamili in ('JF','MI')
AND A1.CODIGO =  A2.AR_CCODIGO COLLATE Modern_Spanish_CI_AI AND A1.TIENDA = @TDA)



-- INSERTA TODOS LOS ARTICULOS NUEVOS DEL REAL
INSERT INTO articulos (TIENDA, CODIGO, STOCK, MINIMO, LISTA1, LISTA2, LISTA3, PLANILLA, USUARIO, FECHA, ESTADO)
(
select DISTINCT @TDA AS TIENDA, 
AR_CCODIGO AS CODIGO , 0 AS STOCK, 2 AS MINIMO, 
AR_NPRECI1 AS LISTA1, AR_NPRECI2 AS LISTA2, AR_NPRECI3 AS LISTA3, 0 AS PLANILLA, 
'SISTEMAS' AS USUARIO, GETDATE() AS FECHA, 'A' AS ESTADO

DECLARE @TDA CHAR(2)
SET @TDA = '05'

SELECT * 
From RSFACCAR..AL0012ARTI AS A2 ,
ARTICULOS  AAA 
WHERE AR_CESTADO='v' AND AR_CFSTOCK='s'  AND  ar_cfamili in ('JF', 'MI' ) 
 AND A2.AR_CCODIGO IS NULL
)


-- DEVUELVE UN RECORDSET CON LOS GRUPOS DE PRENDAS QUE NO TIENEN PRECIO

SELECT * FROM VIEW_ARTICULOS_TIENDA WHERE TIENDA = '05'

SELECT GRUPO, DESCRI FROM VIEW_GRUPOS WHERE TIENDA ='05' GROUP BY GRUPO, DESCRI

--DELETE ARTICULOS WHERE TIENDA ='05'