USE VENTAS

CREATE TABLE [ARTICULOS] (
	[TIENDA]		char(2)		not null references [tiendas](codigo),
	[CODIGO]		char(25) not null ,
	[STOCK]			NUMERIC (4) NOT NULL DEFAULT 0,
	[MINIMO]		NUMERIC (4) NOT NULL DEFAULT 2,
	[LISTA1]		NUMERIC (7,2),
	[LISTA2]		NUMERIC (7,2),
	[LISTA3]		NUMERIC (7,2),
	[USUARIO]		char(10) NOT NULL DEFAULT 'SISTEMAS',
	[FECHA]			SMALLDATETIME DEFAULT GETDATE() NOT NULL,
	[ESTADO]		CHAR(1) DEFAULT 'A' NOT NULL,
PRIMARY KEY (TIENDA,CODIGO)
)