select * from articulos where stock > 0
select * from cAJA ORDER BY OPERACION
SELECT * FROM MOVIMCAB AS M1
INNER JOIN CLIENTES AS C1 ON C1.CLIENTE = M1.CLIENTE
INNER JOIN MOVIMDET AS M2 ON M1.OPERACION = M2.OPERACION
inner join view_ARTICULOS_TIENDA V1 ON
M2.CODART = V1.CODIGO
WHERE M1.OPERACION ='0000000018'
AND M2.SALE > 0 AND V1.TIENDA = '02'
ORDER BY M2.ITEM

SELECT * FROM VIEW_ARTICULOS_TIENDA where stock > 0

(precio - igv + descuento) / m2.sale = pvp

