use ventas
drop table compania
drop table color
drop table adelanto
drop table almacen
drop table aroma
drop table articulo
drop table articulolista
drop table avalista
drop table BANCO
drop table CATEGORIA
drop table CLI_AVAL
drop table COMPRACAB
drop table COMPRADET
drop table CONTENIDO
drop table CTA_BANCO
drop table CTACTECAB
drop table CTACTEDET
drop table DESMONEDA
drop table DISTRITO
drop table FAMIARTI
drop table FILTROS
drop table GENERICOART
drop table HOBBI
drop table IMPUESTO
drop table MONEDA
drop table prodgen
drop table producto
drop table profocab
drop table profodet
drop table provearti
drop table proveedor
drop table punto
drop table rbo_det
drop table recibo
drop table ret_caj
drop table ret_money
drop table retcajacab
drop table retcajadet
drop table SALINI
drop table SUSPECAB
drop table SUSPEDET
drop table TALLA
drop table TESTADO
drop table TIPARTI
drop table TIPCAM
drop table tmovim
drop table ventas000
DROP TABLE CLIENTE
drop table ventadeva