USE [VENTAS]
GO

ALTER TABLE [dbo].[CAJA]			NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[clientes]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[documento]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[tipmov]			NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[usr_tienda]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[USUARIOS]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[articulos]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[tiendas]			NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[movimDET]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[movimcab]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[MOTITRANS]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[VARIOS]			NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[SALDOS]			NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[DESCUENTOS]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[bkp_movimdet]	NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[temporal]		NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[articulos_bkp]	NOCHECK CONSTRAINT ALL


ALTER TABLE [dbo].[movimcab] add
[DESCUENTO1] [numeric](7, 2) NULL

update movimcab set descuento1 = descuento		

ALTER TABLE [dbo].[movimcab] DROP COLUMN descuento
SP_RENAME '[dbo].[movimcab].DESCUENTO1', 'DESCUENTO'
GO
ALTER TABLE [dbo].[CAJA]			CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[clientes]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[documento]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[tipmov]			CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[usr_tienda]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[USUARIOS]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[articulos]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[tiendas]			CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[movimDET]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[movimcab]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[MOTITRANS]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[VARIOS]			CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[SALDOS]			CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[DESCUENTOS]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[bkp_movimdet]	CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[temporal]		CHECK CONSTRAINT ALL
ALTER TABLE [dbo].[articulos_bkp]	CHECK CONSTRAINT ALL