USE VENTAS
GO
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ==================================================
-- Author:		MABEL MOLINA
-- Create date: 24-06-2013
-- Description:	CAPTURA TODOS LAS LINEAS DE CABECERA
--				/DETALLE PARA PASAR AL SOFTCVOM
--				Y GENERAR ASIENTO CONTABLE, REGISTRO
--				DE VENTAS Y DESCARGAR STOCK
-- ==================================================
CREATE PROCEDURE INTERFACE_REAL
	-- Add the parameters for the stored procedure here
	@TDA CHAR(2), 
	@INI SMALLDATETIME,
	@FIN SMALLDATETIME
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	-- TRABAJAMOS FORMATO DE FECHA EN DIA MES AÑO
	set dateformat dmy;
	INSERT INTO RSFACCAR..CF0012FACT (CF_CCODAGE, CF_CTD, CF_CNUMSER, CF_CNUMDOC, 
	CF_DFECDOC,CF_DFECVEN, CF_CVENDE, CF_CCODCLI,CF_CNOMBRE, CF_CDIRECC, CF_CRUC,
	CF_CFORVEN, CF_CALMA, CF_CCODMON, CF_NTIPCAM, CF_CESTADO, CF_CSECUE, CF_CCODIGO, 
	CF_NCANTID, CF_NPRECIO, CF_NIGV, CF_NIMPORT, CF_CCENCOS, CF_CACCANU, CF_CANEX7, 
	CF_CANER7, CF_CAREA7, CF_CFLGFAC, CF_CSUBDIA)
	SELECT CF_CCODAGE, CF_CTD, CF_CNUMSER, CF_CNUMDOC, 
	CF_DFECDOC, CF_DFECVEN, CF_CVENDE, CF_CCODCLI, CF_CNOMBRE, CF_CDIRECC, CF_CRUC,
	CF_CFORVEN, CF_CALMA, CF_CCODMON, CF_NTIPCAM, CF_CESTADO, CF_cSECUE, CF_CCODIGO, 
	CF_NCANTID, CF_NPRECIO, CF_NIGV, CF_NIMPORT, CF_CCENCOS, CF_CACCANU, CF_CANEX7, 
	CF_CANER7, CF_CAREA7, CF_CFLGFAC, CF_CSUBDIA
	FROM 
	(SELECT DISTINCT  TOP 100 PERCENT  '0001' AS CF_CCODAGE, case when M1.coddoc = 'BL' then 'BV' ELSE M1.CODDOC END AS CF_CTD, 
	M1.SERIE AS CF_CNUMSER, M1.NUMDOC AS CF_CNUMDOC, M1.FECDOC AS CF_DFECDOC, M1.FECDOC AS CF_DFECVEN, 
	T1.VENDE AS CF_CVENDE, CASE WHEN RIGHT(M1.CLIENTE,8) IN (SELECT '000000'+CODIGO FROM TIENDAS)
	THEN RIGHT(M1.CLIENTE,8) ELSE SUBSTRING(M1.CLIENTE,3,8)END AS CF_CCODCLI, C1.NOMBRE AS CF_CNOMBRE,
	C1.DIRECCION AS CF_CDIRECC, C1.CLIENTE AS CF_CRUC, '1' AS CF_CFORVEN,
	T1.ALMAC AS CF_CALMA,'MN' AS CF_CCODMON, (SELECT  XMEIMP2 AS ALTO FROM RSCONCAR..CTCAMB WHERE XCODMON = 'US' 
	and xfeccam = right(convert(char(4),year(M1.FECDOC)),2)+right('0'+ltrim(rtrim(CONVERT(CHAR(2), month(m1.fecdoc)))),2)
	+right('0'+ltrim(rtrim(CONVERT(CHAR(2), day(m1.fecdoc)))),2)) AS CF_NTIPCAM, 
	CASE WHEN M1.PVP = 0 THEN 'A' ELSE 'V' END AS CF_CESTADO,
	-- inicia secuencia de detalle de factura / boleta....
	RIGHT('0000'+ LTRIM(RTRIM(M2.ITEM)),4) AS CF_CSECUE, M2.CODART AS CF_CCODIGO, SALE AS CF_NCANTID,
	CASE WHEN M2.SALE > 0 THEN (M2.PRECIO-M2.IGV)/M2.SALE ELSE 0 END AS CF_NPRECIO,
	M2.IGV AS CF_NIGV, M2.PRECIO AS CF_NIMPORT, V1.TC_CCOSVEN AS CF_CCENCOS, '' AS CF_CACCANU, 
	V1.TC_CVENTAS AS CF_CANEX7, '' AS CF_CANER7, '' AS CF_CAREA7,
	'' AS CF_CFLGFAC, '' AS CF_CSUBDIA,
	M1.OPERACION, CONVERT(INTEGER, M2.ITEM)	 as item		
		FROM MOVIMCAB  AS M1 
		INNER JOIN MOVIMDET AS M2 ON M1.OPERACION  = M2.OPERACION
		INNER JOIN TIENDAS AS T1 ON T1.CODIGO = M1.TIENDA
		INNER JOIN CLIENTES AS C1 ON C1.CLIENTE = M1.CLIENTE
		INNER JOIN VIEW_ARTICULOS_TIENDA AS V1 ON V1.TIENDA=M1.TIENDA AND V1.CODIGO = M2.CODART
		WHERE	FECdoc between @INI  AND DateAdd(day,1,@FIN)
				AND CONTA = ''  and M1.TIENDA =ltrim(rtrim(@TDA))
				and tipmov = 'S' AND NOT PVP IS NULL
		ORDER BY M1.OPERACION, CONVERT(INTEGER, M2.ITEM)) ASD
	
	
END
GO
