Select AR_CCODIGO AS CODIGO ,AR_CDESCRI as DESCRI , AR_CUNIDAD AS UNI,AR_NPRECI1 AS LISTA1, AR_NPRECI2 AS LISTA2,
AR_NPRECI3 AS LISTA3, AR_CMONVTA AS MONEDA, AR_NIGVPOR AS IGV
From RSFACCAR..AL0012ARTI WHERE AR_CESTADO='v' AND AR_CFSTOCK='s' 
and ar_ccuenta ='211101' 
 AND (AR_CMARCA IN ('MAIDENF', 'EL MODEL', 'EBERJEY','JACFER','KAYSER') OR ar_cfamili in ('JF','IN'))

SELECT AR_CGRUPO, COUNT(*), MIN(AR_CDESCRI)From
RSFACCAR..AL0012ARTI GROUP BY AR_CGRUPO
ORDER BY 1

SELECT *
From RSFACCAR..AL0012ARTI WHERE AR_CESTADO='v' AND AR_CFSTOCK='s' 
and ar_ccuenta ='211101' 
 AND (AR_CMARCA IN ('MAIDENF', 'EL MODEL', 'EBERJEY','JACFER','KAYSER') OR ar_cfamili in ('JF','IN'))