

SELECT 2015 AS ANIO, 0 AS NMES, '' AS MES, 
	'' AS CTDA, 'ALMACEN FABRICA' AS TIENDA, UPPER(SS.SK_CCODIGO) AS CODIGO, 
	LEFT(SS.SK_CCODIGO,5) AS GRUPO, UPPER(SUBSTRING ( SS.SK_CCODIGO ,9, 2)) AS COLOR, 
	UPPER(SUBSTRING ( SS.SK_CCODIGO ,6, 3)) AS TALLA, 		
	AA.AR_CFAMILI AS CODM, TB.TG_CDESCRI  AS MARCA, 
	AA.AR_CGRUPO   AS CTIP, TR.TG_CDESCRI AS TIP_PDA, 
	ISNULL(CGEN,'G') AS CGEN, ISNULL(DGEN,'GENERICO') AS GENERO,
	AR_CDESCRI  collate Modern_Spanish_CI_AI AS DESCRI, 
	0 AS QTY_VTA, 0 AS STK, SK_NSKDIS AS STK_ALM ,
	0 AS UNIT, 	0 AS PVP, 0 AS PORDES, 0 AS DCT, 0 AS IGV, 0 AS TOT, 
	isnull(te.descripcion, '') as DTEM


--SELECT * FROM RSFACCAR.dbo.AL0012ARTI
FROM RSFACCAR..al0012stoc AS SS 
INNER JOIN  RSFACCAR.dbo.AL0012ARTI AS AA  ON SS.SK_CCODIGO = AA.AR_CCODIGO
INNER JOIN	RSFACCAR.dbo.AL0012TABL AS TB ON AA.AR_CFAMILI = TB.TG_CCLAVE AND TB.TG_CCOD = '38'
INNER JOIN	RSFACCAR.dbo.AL0012TABL AS TR ON AA.AR_CGRUPO = TR.TG_CCLAVE AND TR.TG_CCOD = '06' 
FULL OUTER JOIN VIEW_GENERO_PRENDA AS GG ON GG.ART = LEFT(SS.SK_CCODIGO,5) COLLATE Modern_Spanish_CI_AI
FULL OUTER JOIN TEMPORADAS AS TE ON (ltrim(rtrim(te.codigo)) collate Modern_Spanish_CI_AI =  RIGHT(RTRIM(AR_CDESCRI),4) 
									 OR  ltrim(rtrim(te.codigo)) collate Modern_Spanish_CI_AI =  RIGHT(RTRIM(AR_CDESCRI),2))
WHERE sk_calma='00t1'
