-- DETALLE POR TALLA COLOR ACUMULADO TODOS LOS MESES DE LA TABLA ORIGINAL
SELECT DISTINCT LEFT(AT_CCODIGO,5) AS COD, 
(SELECT TG_CDESCRI FROM RSFACCAR..AL0012TABL WHERE TG_CCOD = '39' AND TG_CCLAVE = SUBSTRING(AT_CCODIGO,1,5)) AS DESCRI,
(SELECT TG_CDESCRI FROM RSFACCAR..AL0012TABL WHERE TG_CCOD = 'D2' AND TG_CCLAVE = SUBSTRING(AT_CCODIGO,9,2)) AS COLOR,
(SELECT TG_CDESCRI FROM RSFACCAR..AL0012TABL WHERE TG_CCOD = 'D1' AND TG_CCLAVE = SUBSTRING(AT_CCODIGO,6,3 )) AS TALLA,
SUM(CANT) AS OCT_FEB 
FROM SKU_RIPLEY
--where  LEFT(AT_CCODIGO,5) = '04704'
GROUP BY  AR_CDESCRI, SUBSTRING(AT_CCODIGO,6,3 ), SUBSTRING(AT_CCODIGO,9,2), SUBSTRING(AT_CCODIGO,1,5)
ORDER BY SUBSTRING(AT_CCODIGO,1,5), COLOR, TALLA


--DELETE RIPLEY WHERE CANT <=0
SELECT * FROM RIPLEY
-- RESUMEN POR GRUPO ACUMULADO TODOS LOS MESES DE LA TABLA ORIGINAL

SELECT DISTINCT LEFT(AT_CCODIGO,5) AS COD, 
SUM(CANT) AS TOTA FROM SKU_RIPLEY
--where  LEFT(AT_CCODIGO,5) = '04704'
GROUP BY LEFT(AT_CCODIGO,5)
