
	
	SET DATEFORMAT DMY;
	SET LANGUAGE SPANISH;
	select DISTINCT YEAR(VV.FECHA) AS ANIO, MONTH(VV.FECHA) AS NMES, UPPER(DATENAME(mm, VV.FECHA)) AS MES, 
	VV.TIENDA AS CTDA, TT.DESCRIPCION AS TIENDA, UPPER(VV.CODART) AS CODIGO, 
	LEFT(VV.CODART,5) AS GRUPO, UPPER(SUBSTRING ( VV.CODART ,9, 2)) AS COLOR, 
	UPPER(SUBSTRING ( VV.CODART ,6, 3)) AS TALLA, 	CODM,MARCA, CLIN AS CTIP, LINEA AS TIP_PDA, 
	ISNULL(CGEN,'G') AS CGEN, ISNULL(DGEN,'GENERICO') AS GENERO,
	VV.DESCRI, SUM (SALE) AS QTY_VTA, (AA.STOCK) AS STK ,
	COSTO,SUM(PRECIO)/SUM(SALE) AS UNIT, 
	SUM(PVP-IGV) AS PVP, AVG(PORDES) AS PORDES, SUM(DCT) AS DCT, SUM(IGV) AS IGV, SUM(PVP) AS TOT, 
	isnull(te.descripcion, '') as DTEM
	FROM VIEW_VENTAS_ARTICULO AS VV
	INNER JOIN TIENDAS AS TT ON  TIENDA = CODIGO
	INNER JOIN VIEW_ARTICULOS_TIENDA AS AA ON AA.TIENDA = VV.TIENDA AND AA.CODIGO = VV.CODART
	INNER JOIN COSTOS CC ON CC.CODIGO = LEFT(CODART,5)
	full outer join temporadas as te on (ltrim(rtrim(te.codigo)) collate Modern_Spanish_CI_AI =  RIGHT(RTRIM(VV.DESCRI),4) or ltrim(rtrim(te.codigo)) collate Modern_Spanish_CI_AI =  RIGHT(RTRIM(VV.DESCRI),2))
	FULL OUTER JOIN VIEW_GENERO_PRENDA GG ON LEFT(VV.CODART,5) = LEFT(GG.ART,5)

	WHERE SALE > 0 and isnull(pvp,0) > 0 
	AND VV.FECHA between '01/01/2012' AND DateAdd(day,1,'31/12/2012') 
	
	AND VV.TIENDA < '20' 

	GROUP BY VV.CODART, VV.DESCRI,  YEAR(VV.FECHA), DATENAME(mm, VV.FECHA), TT.DESCRIPCION, MONTH(VV.FECHA), 
			 VV.TIENDA, AA.STOCK, CODM, CLIN, MARCA, LINEA,COSTO, CGEN, DGEN,RIGHT(RTRIM(VV.DESCRI),4), te.descripcion

	ORDER BY YEAR(VV.FECHA), MONTH(VV.FECHA), VV.TIENDA,  UPPER(VV.CODART)


--	SELECT * FROM ARTICULOS