USE VENTAS
GO
ALTER VIEW VIEW_GENERO_PRENDA
AS

SELECT RIGHT(LTRIM(RTRIM(EE.CODARTICULO)),5) AS ART, EE.GENERO AS CGEN, GG.DESCRIPCION AS DGEN

FROM MODELADOR..ESTILOS AS EE
INNER JOIN MODELADOR..GENEROS AS GG ON GG.GENERO = EE.GENERO
WHERE LEN(RIGHT(LTRIM(RTRIM(EE.CODARTICULO)),5))> 0 AND ISNUMERIC(RIGHT(LTRIM(RTRIM(EE.CODARTICULO)),5)) = 1
GROUP BY RIGHT(LTRIM(RTRIM(EE.CODARTICULO)),5), EE.GENERO, GG.DESCRIPCION
