ALTER VIEW VIEW_COSTOS
AS

SELECT DISTINCT TOP (100) PERCENT C.CODIGO, C.COSTO, MIN(REPLACE(A.AR_CDESCRI, '"', 'PLG')) AS DESCRI, STR(MAX(A.AR_NPRECI6), 12, 2) AS PVP
FROM        RSFACCAR.dbo.AL0012ARTI AS A 
INNER JOIN	dbo.COSTOS AS C ON LEFT(LTRIM(RTRIM(A.AR_CCODIGO)), 5) + '00000' COLLATE Modern_Spanish_CI_AI = LTRIM(RTRIM(C.CODIGO)) + '00000'
WHERE       C.ESTADO = 'a'
GROUP BY C.CODIGO, C.COSTO
ORDER BY C.CODIGO